---
config:
  theme: neo
  look: handDrawn
  layout: elk
---
graph TD
    %% Styling
    classDef pink fill:#ffe4e6,stroke:#e11d48,stroke-width:2px;
    classDef yellow fill:#fef9c3,stroke:#ca8a04,stroke-width:2px;
    classDef green fill:#dcfce7,stroke:#16a34a,stroke-width:2px;
    classDef blue fill:#dbeafe,stroke:#2563eb,stroke-width:2px;
    classDef orange fill:#ffedd5,stroke:#f97316,stroke-width:2px;
    classDef purple fill:#ede9fe,stroke:#7c3aed,stroke-width:2px;
    classDef gray fill:#e2e8f0,stroke:#475569,stroke-width:2px;
    classDef brown fill:#FFE0B2, color:#97705D, fill:#E8DAD4, background-color:#E8DAD4, stroke:#97705D, border-color:#97705D

    %% Nodes
    Home(首頁<br>Home)
    Guest(訪客<br>Guest)
    Admin(後台<br>Admin)

    Search(搜尋<br>Search)
    About(關於<br>About)
    News(動態消息<br>News)

    Login(登入<br>Login)
    Regular(註冊<br>Regular)

    Dashboard(儀表板<br>Dashboard)
    Users(使用者管理<br>Users)
    Articles(貼文管理<br>Articles)
    Report(檢擧管理<br>Report)
    WebLogs(網站設定<br>Web Logs)

    AddArticle(建立貼文<br>Add Article)
    Notify(通知<br>Notify)
    Message(訊息<br>Message)
    Bookmark(書籤<br>Bookmark)
    Profile(個人檔案<br>Profile)
    Settings(設定<br>Settings)

    ProfileHome(個人主頁<br>ProfileHome)
    Activity(活動<br>Activity)
    Praise(按讚<br>Praise)
    Reply(回覆<br>Reply)

    EditProfile(編輯個人資訊<br>EditProfile<br>註冊 stepl)
    EditAccount(帳號設定<br>EditAccount<br>註冊 step2)
    EditSecurity(安全性設定<br>EditSecurity<br>註冊 step3)
    EditWeb3(錢包與數位身分<br>EditWeb3<br>註冊 step4)

    %% Group
    Home --> Guest
    Home --> Login
    Home --> Regular
    Home --> Admin

    Guest --> Search
    Guest --> About
    Guest --> News
    subgraph "訪客"
      Search
      About
      News
    end

    Login --> AddArticle
    Login --> Notify
    Login --> Message
    Login --> Bookmark
    Login --> Profile
    Login --> Settings
    subgraph "會員"
      AddArticle
      Notify
      Message
      Bookmark
      Profile
      Settings

      Profile --> ProfileHome
      Profile --> Activity
      Profile --> Praise
      Profile --> Reply
      subgraph "個人檔案"
        ProfileHome
        Activity
        Praise
        Reply
      end
      
      Settings --> EditProfile
      Settings --> EditAccount
      Settings --> EditSecurity
      Settings --> EditWeb3
      subgraph "設定"
        EditProfile
        EditAccount
        EditSecurity
        EditWeb3
      end
    end

    Admin --> Dashboard
    Admin --> Users
    Admin --> Articles
    Admin --> Report
    Admin --> WebLogs
    subgraph "後台"
      Dashboard
      Users
      Articles
      Report
      WebLogs
    end

    Regular -.-> Settings

    %% %% Apply styles
    class Home pink
    class Guest,Search,About,News brown
    class Login,AddArticle,Notify,Message,Bookmark,Profile,Settings yellow
    class ProfileHome,Activity,Praise,Reply blue
    class Regular green
    class EditProfile,EditAccount,EditSecurity,EditWeb3 purple
    class Admin,Dashboard,Users,Articles,Report,WebLogs gray